<h1>Sarcasm detection system using custom
Naïve Bayes implementations</h1>

In [2]:
import numpy as np
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import re
import json
import math 
from collections import defaultdict, Counter
from sklearn.metrics  import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [3]:
student_ID = 276690

In [4]:
df = pd.read_json('/Users/arjun/Downloads/Data/Sarcasm_Headlines_Dataset.json', lines=True)
print(df.shape)
df.head()

(26709, 3)

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://local.theonion.com/mom-starting-to-fea...,mom starting to fear son's web series closest ...,1
3,https://politics.theonion.com/boehner-just-wan...,"boehner just wants wife to listen, not come up...",1
4,https://www.huffingtonpost.com/entry/jk-rowlin...,j.k. rowling wishes snape happy birthday in th...,0

In [6]:
#shuffling
df_shuffled = df.sample(frac=1, random_state=student_ID)
df_shuffled.head()

,article_link,headline,is_sarcastic
16569,https://www.huffingtonpost.com/entry/samantha-...,samantha bee tells democrats what it'll take t...,0
14939,https://www.huffingtonpost.com/entry/john-oliv...,john oliver: nratv is like a 'deranged letter ...,0
23948,https://www.huffingtonpost.com/entry/republica...,senate's new plan to repeal but not replace ob...,0
8678,https://politics.theonion.com/john-boehner-cal...,john boehner calls for national guard to deal ...,1
5072,https://www.theonion.com/rest-of-world-not-bit...,rest of world not biting on couple's open rela...,1

In [7]:
#70/15/15 split 
n = len(df_shuffled)
training_upper_lim = int(0.7 * n)
validation_upper_lim = int(0.85 * n)
traning_dataset = df_shuffled.iloc[: training_upper_lim]
validation_dataset = df_shuffled.iloc[training_upper_lim:validation_upper_lim]
test_dataset = df_shuffled.iloc[validation_upper_lim:]

In [10]:
print(n)
print(f'train dataset count : {len(traning_dataset)}')
print(f'validation dataset count : {len(validation_dataset)}')
print(f'test dataset count : {len(test_dataset)}')
total = len(traning_dataset) + len(validation_dataset) + len(test_dataset)
print(f'{'count verified'if total ==n else 'mismatch in count'}')

26709
train dataset count : 18696
validation dataset count : 4006
test dataset count : 4007
count verified

In [13]:
#smoothing
smoothing_sets = {
    0: [0, 0.1, 1],
    1: [0, 0.5, 2],
    2: [0, 1,   5],
}
k = student_ID % 4

**Task 1 – Tokenisation & Preprocessing**

In [23]:
#basic cleaning
def basic_cleaning (text):
     text = text.lower()
     text = re.sub(r"<.*?>", "", text) #html
     text = re.sub(r'!{2,}',    '[EXC_SEQ]',  text) #Exclamation Sequences: !!, !!!, etc. à[EXC_SEQ]
     text = re.sub(r'\?{2,}',   '[QUE_SEQ]',  text)  #Question Sequences: ??, ???, etc. à[QUE_SEQ]
     text = re.sub(r'[?!]{2,}', '[INT_MARK]', text)  #Interrobangs: Any combination of ?! or !? à[INT_MARK]
     text = re.sub(r'\.{3,}',   '[ELLIP]',    text) #Ellipses: ... à [ELLIP]

     text = re.sub(r"[^\w\s']",       '', text)   # remove non word/space/apostrophe
     text = re.sub(r"(?<!\w)'|'(?!\w)", '', text)  # remove apostrophes NOT inside words

     text = re.findall(r'\[.*?\]|\w+(?:\'\w+)*', text)
     return text

references:
https://www.geeksforgeeks.org/python/how-to-remove-html-tags-from-string-in-python/

https://regex101.com/

https://docs.python.org/3/library/re.html#re.sub #pattern substitution

In [16]:
df_shuffled['headline'].iloc[1]

"john oliver: nratv is like a 'deranged letter from a serial killer'"

In [37]:
#testing regex
sample_headlines = [
    "Scientists DISCOVER!!! That Water Is WET!!",   
    "Are? you?? serious????",             
    "Oh reaLly?! come on!!??",      
    "just waiting...",    
    "<b>Breaking news</b>: bomb blast", 
    "senate's new plan to [repeal] but not replace",  
    "a 'damn' letter from a serial killer",    
]

data=[]
for i in sample_headlines:
    word = basic_cleaning(i)
    print(word)

['scientists', 'discoverEXC_SEQ', 'that', 'water', 'is', 'wetEXC_SEQ']
['are', 'youQUE_SEQ', 'seriousQUE_SEQ']
['oh', 'reallyINT_MARK', 'come', 'onEXC_SEQQUE_SEQ']
['just', 'waitingELLIP']
['breaking', 'news', 'bomb', 'blast']
["senate's", 'new', 'plan', 'to', 'repeal', 'but', 'not', 'replace']
['a', 'damn', 'letter', 'from', 'a', 'serial', 'killer']